import type { Product } from '@/types/sale'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'JOKER T-SHIRT ML-TE15',
    price: 240000,
    stock: 10,
    category: 'T-Shirts',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-thun',
    brand: 'Yonex',
    color: ['red', 'black'],
    material: ['100% Cotton'],
    spec: ['Yonex'],
  },
  {
    id: '2',
    name: 'HARLEY QUINN T-SHIRT ML',
    price: 240000,
    stock: 0,
    category: 'T-Shirts',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-thun',
    brand: 'Adidas',
    color: ['pink'],
    material: ['Polyester'],
    spec: ['Adidas'],
  },
  {
    id: '3',
    name: 'YONEX BADMINTON SHIRT',
    price: 0,
    stock: 5,
    category: 'Sports Wear',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-the-thao',
    brand: 'Yonex',
    color: ['blue', 'green'],
    material: ['Polyester'],
    spec: ['Yonex'],
  },
  {
    id: '4',
    name: 'NIKE AIR MAX SNEAKERS',
    price: 1200000,
    stock: 8,
    category: 'Footwear',
    image: '/api/placeholder/150/150',
    group: 'giay/giay-the-thao',
    brand: 'Nike',
    color: ['black', 'white'],
    material: ['Kaki'],
    spec: ['Nike'],
  },
  {
    id: '5',
    name: 'ADIDAS RUNNING SHORTS',
    price: 320000,
    stock: 15,
    category: 'Sports Wear',
    image: '/api/placeholder/150/150',
    group: 'quan/quan-ngan',
    brand: 'Adidas',
    color: ['blue'],
    material: ['Polyester'],
    spec: ['Adidas'],
  },
  {
    id: '6',
    name: "LEVI'S DENIM JEANS",
    price: 850000,
    stock: 12,
    category: 'Jeans',
    image: '/api/placeholder/150/150',
    group: 'quan/quan-jean',
    brand: "Levi's",
    color: ['blue'],
    material: ['100% Cotton'],
    spec: ["Levi's"],
  },
  {
    id: '7',
    name: 'POLO RALPH LAUREN SHIRT',
    price: 680000,
    stock: 6,
    category: 'Shirts',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-thun',
    brand: 'Polo Ralph Lauren',
    color: ['white'],
    material: ['100% Cotton'],
    spec: ['Polo Ralph Lauren'],
  },
  {
    id: '8',
    name: 'CHAMPION HOODIE',
    price: 540000,
    stock: 20,
    category: 'Hoodies',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-khoac',
    brand: 'Champion',
    color: ['black'],
    material: ['100% Cotton'],
    spec: ['Champion'],
  },
  {
    id: '9',
    name: 'CONVERSE CHUCK TAYLOR',
    price: 750000,
    stock: 0,
    category: 'Footwear',
    image: '/api/placeholder/150/150',
    group: 'giay/giay-the-thao',
    brand: 'Converse',
    color: ['white'],
    material: ['Leather'],
    spec: ['Converse'],
  },
  {
    id: '10',
    name: 'UNDER ARMOUR TANK TOP',
    price: 280000,
    stock: 25,
    category: 'Sports Wear',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-thun',
    brand: 'Under Armour',
    color: ['black'],
    material: ['80% Cotton', '20% Polyester'],
    spec: ['Under Armour'],
  },
  {
    id: '11',
    name: 'H&M CASUAL DRESS',
    price: 420000,
    stock: 18,
    category: 'Dresses',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-dang',
    brand: 'H&M',
    color: ['black'],
    material: ['100% Polyester'],
    spec: ['H&M'],
  },
  {
    id: '12',
    name: 'ZARA LEATHER JACKET',
    price: 1500000,
    stock: 4,
    category: 'Jackets',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-khoac',
    brand: 'Zara',
    color: ['black'],
    material: ['100% Leather'],
    spec: ['Zara'],
  },
  {
    id: '13',
    name: 'UNIQLO BASIC TEE',
    price: 150000,
    stock: 50,
    category: 'T-Shirts',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-thun',
    brand: 'Uniqlo',
    color: ['white'],
    material: ['100% Cotton'],
    spec: ['Uniqlo'],
  },
  {
    id: '14',
    name: 'PUMA TRAINING PANTS',
    price: 480000,
    stock: 14,
    category: 'Sports Wear',
    image: '/api/placeholder/150/150',
    group: 'quan/quan-the-thao',
    brand: 'Puma',
    color: ['black'],
    material: ['80% Polyester', '20% Spandex'],
    spec: ['Puma'],
  },
  {
    id: '15',
    name: 'TOMMY HILFIGER POLO',
    price: 620000,
    stock: 9,
    category: 'Polo Shirts',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-thun',
    brand: 'Tommy Hilfiger',
    color: ['white'],
    material: ['100% Cotton'],
    spec: ['Tommy Hilfiger'],
  },
  {
    id: '16',
    name: 'VANS OLD SKOOL',
    price: 900000,
    stock: 11,
    category: 'Footwear',
    image: '/api/placeholder/150/150',
    group: 'giay/giay-the-thao',
    brand: 'Vans',
    color: ['black'],
    material: ['Leather'],
    spec: ['Vans'],
  },
  {
    id: '17',
    name: 'GAP CHINO PANTS',
    price: 580000,
    stock: 16,
    category: 'Pants',
    image: '/api/placeholder/150/150',
    group: 'quan/quan-jean',
    brand: 'GAP',
    color: ['blue'],
    material: ['100% Cotton'],
    spec: ['GAP'],
  },
  {
    id: '18',
    name: 'NEW BALANCE RUNNING SHOES',
    price: 1100000,
    stock: 7,
    category: 'Footwear',
    image: '/api/placeholder/150/150',
    group: 'giay/giay-the-thao',
    brand: 'New Balance',
    color: ['white'],
    material: ['Leather'],
    spec: ['New Balance'],
  },
  {
    id: '19',
    name: 'CALVIN KLEIN UNDERWEAR SET',
    price: 350000,
    stock: 30,
    category: 'Underwear',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Calvin Klein',
    color: ['black'],
    material: ['95% Cotton', '5% Elastane'],
    spec: ['Calvin Klein'],
  },
  {
    id: '20',
    name: 'LACOSTE TENNIS SHIRT',
    price: 720000,
    stock: 8,
    category: 'Sports Wear',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-thun',
    brand: 'Lacoste',
    color: ['green'],
    material: ['100% Cotton'],
    spec: ['Lacoste'],
  },
  {
    id: '21',
    name: 'FOREVER 21 CROP TOP',
    price: 180000,
    stock: 22,
    category: 'Tops',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-thun',
    brand: 'Forever 21',
    color: ['black'],
    material: ['100% Polyester'],
    spec: ['Forever 21'],
  },
  {
    id: '22',
    name: 'BOSS FORMAL SHIRT',
    price: 980000,
    stock: 5,
    category: 'Formal Wear',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-thun',
    brand: 'Boss',
    color: ['white'],
    material: ['100% Cotton'],
    spec: ['Boss'],
  },
  {
    id: '23',
    name: 'REEBOK CROSSFIT SHOES',
    price: 1300000,
    stock: 6,
    category: 'Footwear',
    image: '/api/placeholder/150/150',
    group: 'giay/giay-the-thao',
    brand: 'Reebok',
    color: ['black'],
    material: ['Leather'],
    spec: ['Reebok'],
  },
  {
    id: '24',
    name: 'MANGO BLAZER',
    price: 890000,
    stock: 10,
    category: 'Blazers',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-khoac',
    brand: 'Mango',
    color: ['black'],
    material: ['100% Polyester'],
    spec: ['Mango'],
  },
  {
    id: '25',
    name: 'DICKIES WORK PANTS',
    price: 460000,
    stock: 18,
    category: 'Work Wear',
    image: '/api/placeholder/150/150',
    group: 'quan/quan-jean',
    brand: 'Dickies',
    color: ['black'],
    material: ['100% Cotton'],
    spec: ['Dickies'],
  },
  {
    id: '26',
    name: 'SUPREME BOX LOGO TEE',
    price: 2500000,
    stock: 2,
    category: 'Limited Edition',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-thun',
    brand: 'Supreme',
    color: ['white'],
    material: ['100% Cotton'],
    spec: ['Supreme'],
  },
  {
    id: '27',
    name: 'PATAGONIA FLEECE JACKET',
    price: 1400000,
    stock: 7,
    category: 'Outdoor Wear',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-khoac',
    brand: 'Patagonia',
    color: ['black'],
    material: ['80% Cotton', '20% Polyester'],
    spec: ['Patagonia'],
  },
  {
    id: '28',
    name: 'LULULEMON YOGA PANTS',
    price: 920000,
    stock: 13,
    category: 'Activewear',
    image: '/api/placeholder/150/150',
    group: 'quan/quan-the-thao',
    brand: 'Lululemon',
    color: ['black'],
    material: ['95% Cotton', '5% Spandex'],
    spec: ['Lululemon'],
  },
  {
    id: '29',
    name: 'TIMBERLAND BOOTS',
    price: 1800000,
    stock: 4,
    category: 'Boots',
    image: '/api/placeholder/150/150',
    group: 'giay/giay-the-thao',
    brand: 'Timberland',
    color: ['brown'],
    material: ['Leather'],
    spec: ['Timberland'],
  },
  {
    id: '30',
    name: 'APPLE WATCH SPORT BAND',
    price: 650000,
    stock: 25,
    category: 'Accessories',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Apple',
    color: ['black'],
    material: ['Silicon'],
    spec: ['Apple'],
  },
  {
    id: '31',
    name: 'RAY-BAN SUNGLASSES',
    price: 1600000,
    stock: 8,
    category: 'Accessories',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Ray-Ban',
    color: ['black'],
    material: ['Leather'],
    spec: ['Ray-Ban'],
  },
  {
    id: '32',
    name: 'CARHARTT BEANIE',
    price: 220000,
    stock: 35,
    category: 'Accessories',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Carhartt',
    color: ['black'],
    material: ['100% Wool'],
    spec: ['Carhartt'],
  },
  {
    id: '33',
    name: 'GUESS HANDBAG',
    price: 1200000,
    stock: 6,
    category: 'Bags',
    image: '/api/placeholder/150/150',
    group: 'tui-xach/tui-xach',
    brand: 'Guess',
    color: ['brown'],
    material: ['Leather'],
    spec: ['Guess'],
  },
  {
    id: '34',
    name: 'SAMSUNG GALAXY WATCH',
    price: 3500000,
    stock: 12,
    category: 'Electronics',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Samsung',
    color: ['black'],
    material: ['Silicon'],
    spec: ['Samsung'],
  },
  {
    id: '35',
    name: 'LOUIS VUITTON WALLET',
    price: 4200000,
    stock: 3,
    category: 'Luxury Accessories',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Louis Vuitton',
    color: ['brown'],
    material: ['Leather'],
    spec: ['Louis Vuitton'],
  },
  {
    id: '36',
    name: 'NIKE DUNK LOW SNEAKERS',
    price: 1350000,
    stock: 15,
    category: 'Footwear',
    image: '/api/placeholder/150/150',
    group: 'giay/giay-the-thao',
    brand: 'Nike',
    color: ['white'],
    material: ['Leather'],
    spec: ['Nike'],
  },
  {
    id: '37',
    name: 'PATAGONIA BACKPACK',
    price: 890000,
    stock: 8,
    category: 'Bags',
    image: '/api/placeholder/150/150',
    group: 'tui-xach/tui-xach',
    brand: 'Patagonia',
    color: ['black'],
    material: ['100% Polyester'],
    spec: ['Patagonia'],
  },
  {
    id: '38',
    name: 'OAKLEY SPORTS GLASSES',
    price: 1100000,
    stock: 11,
    category: 'Sports Accessories',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Oakley',
    color: ['black'],
    material: ['Polarized'],
    spec: ['Oakley'],
  },
  {
    id: '39',
    name: 'COLUMBIA WINDBREAKER',
    price: 650000,
    stock: 19,
    category: 'Outdoor Wear',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-khoac',
    brand: 'Columbia',
    color: ['black'],
    material: ['100% Polyester'],
    spec: ['Columbia'],
  },
  {
    id: '40',
    name: 'DIESEL RIPPED JEANS',
    price: 950000,
    stock: 7,
    category: 'Jeans',
    image: '/api/placeholder/150/150',
    group: 'quan/quan-jean',
    brand: 'Diesel',
    color: ['blue'],
    material: ['100% Cotton'],
    spec: ['Diesel'],
  },
  {
    id: '41',
    name: 'ROLEX SUBMARINER REPLICA',
    price: 8500000,
    stock: 1,
    category: 'Luxury Watches',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Rolex',
    color: ['black'],
    material: ['Stainless Steel'],
    spec: ['Rolex'],
  },
  {
    id: '42',
    name: 'BALENCIAGA SPEED TRAINER',
    price: 6200000,
    stock: 2,
    category: 'Designer Footwear',
    image: '/api/placeholder/150/150',
    group: 'giay/giay-the-thao',
    brand: 'Balenciaga',
    color: ['black'],
    material: ['Leather'],
    spec: ['Balenciaga'],
  },
  {
    id: '43',
    name: 'NORTHFACE PUFFER JACKET',
    price: 1850000,
    stock: 9,
    category: 'Winter Wear',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-khoac',
    brand: 'The North Face',
    color: ['black'],
    material: ['80% Polyester', '20% Down'],
    spec: ['The North Face'],
  },
  {
    id: '44',
    name: 'LEVIS 501 ORIGINAL JEANS',
    price: 780000,
    stock: 23,
    category: 'Jeans',
    image: '/api/placeholder/150/150',
    group: 'quan/quan-jean',
    brand: "Levi's",
    color: ['blue'],
    material: ['100% Cotton'],
    spec: ["Levi's"],
  },
  {
    id: '45',
    name: 'APPLE AIRPODS PRO',
    price: 3200000,
    stock: 17,
    category: 'Electronics',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Apple',
    color: ['white'],
    material: ['Silicon'],
    spec: ['Apple'],
  },
  {
    id: '46',
    name: 'YEEZY BOOST 350',
    price: 2800000,
    stock: 4,
    category: 'Limited Sneakers',
    image: '/api/placeholder/150/150',
    group: 'giay/giay-the-thao',
    brand: 'Adidas',
    color: ['black'],
    material: ['Leather'],
    spec: ['Adidas'],
  },
  {
    id: '47',
    name: 'GUCCI BELT',
    price: 5500000,
    stock: 6,
    category: 'Luxury Accessories',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Gucci',
    color: ['brown'],
    material: ['Leather'],
    spec: ['Gucci'],
  },
  {
    id: '48',
    name: 'CHAMPION SWEATPANTS',
    price: 420000,
    stock: 28,
    category: 'Sports Wear',
    image: '/api/placeholder/150/150',
    group: 'quan/quan-the-thao',
    brand: 'Champion',
    color: ['black'],
    material: ['100% Cotton'],
    spec: ['Champion'],
  },
  {
    id: '49',
    name: 'VERSACE SUNGLASSES',
    price: 2200000,
    stock: 5,
    category: 'Designer Accessories',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Versace',
    color: ['black'],
    material: ['Leather'],
    spec: ['Versace'],
  },
  {
    id: '50',
    name: 'HERSCHEL SUPPLY BACKPACK',
    price: 680000,
    stock: 14,
    category: 'Bags',
    image: '/api/placeholder/150/150',
    group: 'tui-xach/tui-xach',
    brand: 'Herschel',
    color: ['black'],
    material: ['100% Polyester'],
    spec: ['Herschel'],
  },
  {
    id: '51',
    name: 'STONE ISLAND HOODIE',
    price: 3800000,
    stock: 3,
    category: 'Designer Wear',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-khoac',
    brand: 'Stone Island',
    color: ['black'],
    material: ['100% Cotton'],
    spec: ['Stone Island'],
  },
  {
    id: '52',
    name: 'DR MARTENS BOOTS',
    price: 1450000,
    stock: 12,
    category: 'Boots',
    image: '/api/placeholder/150/150',
    group: 'giay/giay-the-thao',
    brand: 'Dr. Martens',
    color: ['black'],
    material: ['Leather'],
    spec: ['Dr. Martens'],
  },
  {
    id: '53',
    name: 'RALPH LAUREN POLO SHIRT',
    price: 580000,
    stock: 21,
    category: 'Polo Shirts',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-thun',
    brand: 'Ralph Lauren',
    color: ['white'],
    material: ['100% Cotton'],
    spec: ['Ralph Lauren'],
  },
  {
    id: '54',
    name: 'JORDAN 1 RETRO HIGH',
    price: 1950000,
    stock: 8,
    category: 'Basketball Shoes',
    image: '/api/placeholder/150/150',
    group: 'giay/giay-the-thao',
    brand: 'Nike',
    color: ['black'],
    material: ['Leather'],
    spec: ['Nike'],
  },
  {
    id: '55',
    name: 'CANADA GOOSE PARKA',
    price: 4500000,
    stock: 2,
    category: 'Luxury Outerwear',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-khoac',
    brand: 'Canada Goose',
    color: ['black'],
    material: ['100% Goose Down'],
    spec: ['Canada Goose'],
  },
  {
    id: '56',
    name: 'FJALLRAVEN KANKEN BACKPACK',
    price: 750000,
    stock: 16,
    category: 'Outdoor Bags',
    image: '/api/placeholder/150/150',
    group: 'tui-xach/tui-xach',
    brand: 'Fjallraven',
    color: ['black'],
    material: ['100% Polyester'],
    spec: ['Fjallraven'],
  },
  {
    id: '57',
    name: 'MONCLER DOWN VEST',
    price: 3200000,
    stock: 4,
    category: 'Designer Outerwear',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-khoac',
    brand: 'Moncler',
    color: ['black'],
    material: ['100% Polyester'],
    spec: ['Moncler'],
  },
  {
    id: '58',
    name: 'ASICS GEL KAYANO RUNNING SHOES',
    price: 1280000,
    stock: 13,
    category: 'Running Shoes',
    image: '/api/placeholder/150/150',
    group: 'giay/giay-the-thao',
    brand: 'Asics',
    color: ['black'],
    material: ['Leather'],
    spec: ['Asics'],
  },
  {
    id: '59',
    name: 'CARHARTT WORK JACKET',
    price: 890000,
    stock: 18,
    category: 'Work Wear',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-khoac',
    brand: 'Carhartt',
    color: ['black'],
    material: ['100% Cotton'],
    spec: ['Carhartt'],
  },
  {
    id: '60',
    name: 'BOSE WIRELESS HEADPHONES',
    price: 2800000,
    stock: 9,
    category: 'Electronics',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Bose',
    color: ['black'],
    material: ['Plastic'],
    spec: ['Bose'],
  },
  {
    id: '61',
    name: 'OFF WHITE T-SHIRT',
    price: 4800000,
    stock: 1,
    category: 'Streetwear',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-thun',
    brand: 'Off White',
    color: ['white'],
    material: ['100% Cotton'],
    spec: ['Off White'],
  },
  {
    id: '62',
    name: 'PATAGONIA FLEECE PULLOVER',
    price: 1150000,
    stock: 11,
    category: 'Outdoor Wear',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-khoac',
    brand: 'Patagonia',
    color: ['black'],
    material: ['80% Cotton', '20% Polyester'],
    spec: ['Patagonia'],
  },
  {
    id: '63',
    name: 'SONY WH-1000XM5 HEADPHONES',
    price: 3500000,
    stock: 7,
    category: 'Electronics',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Sony',
    color: ['black'],
    material: ['Plastic'],
    spec: ['Sony'],
  },
  {
    id: '64',
    name: 'MIZUNO RUNNING SHOES',
    price: 1250000,
    stock: 10,
    category: 'Footwear',
    image: '/api/placeholder/150/150',
    group: 'giay/giay-the-thao',
    brand: 'Mizuno',
    color: ['yellow', 'blue'],
    material: ['Mesh'],
    spec: ['Mizuno'],
  },
  {
    id: '65',
    name: 'CROCS CLASSIC CLOG',
    price: 600000,
    stock: 20,
    category: 'Footwear',
    image: '/api/placeholder/150/150',
    group: 'dep/dep',
    brand: 'Crocs',
    color: ['green', 'pink'],
    material: ['Rubber'],
    spec: ['Crocs'],
  },
  {
    id: '66',
    name: 'BURBERRY SCARF',
    price: 3200000,
    stock: 5,
    category: 'Accessories',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Burberry',
    color: ['yellow', 'brown'],
    material: ['Wool'],
    spec: ['Burberry'],
  },
  {
    id: '67',
    name: 'GUESS DENIM JACKET',
    price: 1100000,
    stock: 7,
    category: 'Jackets',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-khoac',
    brand: 'Guess',
    color: ['blue'],
    material: ['Denim'],
    spec: ['Guess'],
  },
  {
    id: '68',
    name: 'ZARA SUMMER DRESS',
    price: 700000,
    stock: 12,
    category: 'Dresses',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-dang',
    brand: 'Zara',
    color: ['pink', 'white'],
    material: ['Linen'],
    spec: ['Zara'],
  },
  {
    id: '69',
    name: 'HERMES LEATHER BELT',
    price: 5200000,
    stock: 2,
    category: 'Luxury Accessories',
    image: '/api/placeholder/150/150',
    group: 'phu-kien/do-lot',
    brand: 'Hermes',
    color: ['brown', 'black'],
    material: ['Leather'],
    spec: ['Hermes'],
  },
  {
    id: '70',
    name: 'UNIQLO AIRISM TEE',
    price: 250000,
    stock: 30,
    category: 'T-Shirts',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-thun',
    brand: 'Uniqlo',
    color: ['blue', 'white'],
    material: ['Polyester'],
    spec: ['Uniqlo'],
  },
  {
    id: '71',
    name: 'LACOSTE POLO DRESS',
    price: 950000,
    stock: 8,
    category: 'Dresses',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-dang',
    brand: 'Lacoste',
    color: ['green'],
    material: ['Cotton'],
    spec: ['Lacoste'],
  },
  {
    id: '72',
    name: 'ADIDAS TRACK JACKET',
    price: 850000,
    stock: 15,
    category: 'Jackets',
    image: '/api/placeholder/150/150',
    group: 'ao/ao-khoac',
    brand: 'Adidas',
    color: ['red', 'black'],
    material: ['Polyester'],
    spec: ['Adidas'],
  },
  {
    id: '73',
    name: 'PUMA RUNNING SHORTS',
    price: 350000,
    stock: 18,
    category: 'Sports Wear',
    image: '/api/placeholder/150/150',
    group: 'quan/quan-ngan',
    brand: 'Puma',
    color: ['yellow', 'black'],
    material: ['Polyester'],
    spec: ['Puma'],
  },
].map((p) => {
  const { group, brand, color, material, spec, ...rest } = p
  return {
    group: typeof group !== 'undefined' ? group : '',
    brand: typeof brand !== 'undefined' ? brand : '',
    color: typeof color !== 'undefined' ? color : [],
    material: typeof material !== 'undefined' ? material : [],
    spec: typeof spec !== 'undefined' ? spec : [],
    ...rest,
  }
})
