/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SaleImport } from './routes/sale'
import { Route as RepairImport } from './routes/repair'
import { Route as PaymentImport } from './routes/payment'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PostsIndexImport } from './routes/posts/index'
import { Route as PostsAddImport } from './routes/posts/add'

// Create/Update Routes

const SaleRoute = SaleImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRoute,
} as any)

const RepairRoute = RepairImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRoute,
} as any)

const PaymentRoute = PaymentImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any)

const PostsAddRoute = PostsAddImport.update({
  id: '/posts/add',
  path: '/posts/add',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentImport
      parentRoute: typeof rootRoute
    }
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairImport
      parentRoute: typeof rootRoute
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleImport
      parentRoute: typeof rootRoute
    }
    '/posts/add': {
      id: '/posts/add'
      path: '/posts/add'
      fullPath: '/posts/add'
      preLoaderRoute: typeof PostsAddImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/payment': typeof PaymentRoute
  '/repair': typeof RepairRoute
  '/sale': typeof SaleRoute
  '/posts/add': typeof PostsAddRoute
  '/posts': typeof PostsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/payment': typeof PaymentRoute
  '/repair': typeof RepairRoute
  '/sale': typeof SaleRoute
  '/posts/add': typeof PostsAddRoute
  '/posts': typeof PostsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/payment': typeof PaymentRoute
  '/repair': typeof RepairRoute
  '/sale': typeof SaleRoute
  '/posts/add': typeof PostsAddRoute
  '/posts/': typeof PostsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/payment'
    | '/repair'
    | '/sale'
    | '/posts/add'
    | '/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/payment'
    | '/repair'
    | '/sale'
    | '/posts/add'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/payment'
    | '/repair'
    | '/sale'
    | '/posts/add'
    | '/posts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PaymentRoute: typeof PaymentRoute
  RepairRoute: typeof RepairRoute
  SaleRoute: typeof SaleRoute
  PostsAddRoute: typeof PostsAddRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PaymentRoute: PaymentRoute,
  RepairRoute: RepairRoute,
  SaleRoute: SaleRoute,
  PostsAddRoute: PostsAddRoute,
  PostsIndexRoute: PostsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/payment",
        "/repair",
        "/sale",
        "/posts/add",
        "/posts/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/payment": {
      "filePath": "payment.tsx"
    },
    "/repair": {
      "filePath": "repair.tsx"
    },
    "/sale": {
      "filePath": "sale.tsx"
    },
    "/posts/add": {
      "filePath": "posts/add.tsx"
    },
    "/posts/": {
      "filePath": "posts/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
