/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrahangRouteImport } from './routes/trahang'
import { Route as TestRouteImport } from './routes/test'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as RepairAddRouteImport } from './routes/repair-add'
import { Route as RepairRouteImport } from './routes/repair'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsAddRouteImport } from './routes/posts/add'

const TrahangRoute = TrahangRouteImport.update({
  id: '/trahang',
  path: '/trahang',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairAddRoute = RepairAddRouteImport.update({
  id: '/repair-add',
  path: '/repair-add',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairRoute = RepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsAddRoute = PostsAddRouteImport.update({
  id: '/posts/add',
  path: '/posts/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/payment': typeof PaymentRoute
  '/repair': typeof RepairRoute
  '/repair-add': typeof RepairAddRoute
  '/sale': typeof SaleRoute
  '/test': typeof TestRoute
  '/trahang': typeof TrahangRoute
  '/posts/add': typeof PostsAddRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/payment': typeof PaymentRoute
  '/repair': typeof RepairRoute
  '/repair-add': typeof RepairAddRoute
  '/sale': typeof SaleRoute
  '/test': typeof TestRoute
  '/trahang': typeof TrahangRoute
  '/posts/add': typeof PostsAddRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/payment': typeof PaymentRoute
  '/repair': typeof RepairRoute
  '/repair-add': typeof RepairAddRoute
  '/sale': typeof SaleRoute
  '/test': typeof TestRoute
  '/trahang': typeof TrahangRoute
  '/posts/add': typeof PostsAddRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/payment'
    | '/repair'
    | '/repair-add'
    | '/sale'
    | '/test'
    | '/trahang'
    | '/posts/add'
    | '/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/payment'
    | '/repair'
    | '/repair-add'
    | '/sale'
    | '/test'
    | '/trahang'
    | '/posts/add'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/payment'
    | '/repair'
    | '/repair-add'
    | '/sale'
    | '/test'
    | '/trahang'
    | '/posts/add'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PaymentRoute: typeof PaymentRoute
  RepairRoute: typeof RepairRoute
  RepairAddRoute: typeof RepairAddRoute
  SaleRoute: typeof SaleRoute
  TestRoute: typeof TestRoute
  TrahangRoute: typeof TrahangRoute
  PostsAddRoute: typeof PostsAddRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trahang': {
      id: '/trahang'
      path: '/trahang'
      fullPath: '/trahang'
      preLoaderRoute: typeof TrahangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair-add': {
      id: '/repair-add'
      path: '/repair-add'
      fullPath: '/repair-add'
      preLoaderRoute: typeof RepairAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/add': {
      id: '/posts/add'
      path: '/posts/add'
      fullPath: '/posts/add'
      preLoaderRoute: typeof PostsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PaymentRoute: PaymentRoute,
  RepairRoute: RepairRoute,
  RepairAddRoute: RepairAddRoute,
  SaleRoute: SaleRoute,
  TestRoute: TestRoute,
  TrahangRoute: TrahangRoute,
  PostsAddRoute: PostsAddRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
